language: haskell

ghc:
  - 7.8

install:
  - cabal install servant servant-client servant-docs servant-jquery --enable-tests

script:
  - cd servant && cabal test
  - cd servant-client && cabal test
  - cd servant-docs && cabal test
  - cd servant-jquery && cabal test

notifications:
  email:
    - alpmestan@gmail.com
    - soenke.hahn@zalora.com
