language: haskell

script:
  - cd servant && cabal install --only-d && cabal configure && cabal build
  - cd servant-pool && cabal sandbox init && cabal sandbox add-source ../servant && cabal install --only-d && cabal configure && cabal build
  - cd servant-postgresql && cabal sandbox init && cabal sandbox add-source ../servant && cabal install --only-d && cabal configure && cabal build
before_install:
  - cabal update
  
notifications:
  email:
      - alp@zalora.com
  irc: "irc.freenode.org#haskell-math"
