language: haskell

ghc:
  - 7.8
  - 7.6

before_install:
  - cabal update
install:
  - ./init.sh
script:
  - ./build.sh
  
notifications:
  email:
      - alp@zalora.com
  irc: "irc.freenode.org#haskell-math"
