language: haskell

ghc:
  - 7.8

env:
  - PACKAGE_DIR=servant
  - PACKAGE_DIR=servant-client
  - PACKAGE_DIR=servant-docs
  - PACKAGE_DIR=servant-jquery

before_install:
  - cd $PACKAGE_DIR

notifications:
  email:
    - alpmestan@gmail.com
    - soenke.hahn@zalora.com
