language: haskell

ghc:
  - 7.8

before_install:
  - cabal install servant/ servant-client/ servant-docs/ servant-jquery/ --only-dependencies --enable-tests

install:
  - |
    for pkg in servant servant-client servant-docs servant-jquery
    do
      cd $pkg && cabal install
    done


script:
  - |
    for pkg in servant servant-client servant-docs servant-jquery
    do
      if [ -d "$pkg/test" ]; then
        cd $pkg && cabal configure --enable-tests && cabal test
      fi
    done

notifications:
  irc:
    channels:
      - "irc.freenode.org#servant"
    template:
      - "%{repository}#%{build_number} - %{commit} on %{branch} by %{author}: %{message}"
      - "Build details: %{build_url} - Change view: %{compare_url}"
    skip_join: true
    on_success: change
    on_failure: always
