language: haskell

ghc:
  - 7.8

script:
  - cabal install servant/ servant-client/ servant-docs/ servant-jquery/ --enable-tests

notifications:
  email:
    - alpmestan@gmail.com
    - soenke.hahn@zalora.com
